apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/vetr/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sat, 06 Dec 2025 14:10:44 MSK
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    server: https://127.0.0.1:32771
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 06 Dec 2025 14:10:44 MSK
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
users:
- name: minikube
  user:
    client-certificate: /home/vetr/.minikube/profiles/minikube/client.crt
    client-key: /home/vetr/.minikube/profiles/minikube/client.key
